name: Send Python weekly summary to telegram bot

on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/**/*-weekly.md'   # when adding weekly file
      - '!docs/en/**/*-weekly.md'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r resources/requirements.txt

      - name: Generate weekly summary
        run: |
          python resources/weekly_summary.py
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          ONLINE_ACTION: 'True'
